### ISSUE TITLE
Как установить rGitHub?

### ISSUE THREAD

**Issue by it19862** [selesnow/rGitHub#1]
Куда вводить команды?

Цитата:
_"Установка пакета осуществляется из репозитория GitHub, для этого сначала требуется установить и подключить пакет devtools.

install.packages("devtools")

library(devtools)"_

**PS**
Прошу прощения если вопрос элементарный.
Только осваиваю..

**Comment by selesnow** [comment]
Здравствуйте, вопрос элементарный для тех кто с R сталкивался, вы видимо пока не сталкивались поэтому вопрос нормальный.

Смотрите изначально вам надо скачать и установить язык R на свой ПК, скачать актуальную версию для своей ОС можно тут - https://cran.r-project.org/bin/windows/base/

Далее для удобства работы рекомендую скачать интегрированную среду разработки RStudio, скачать её можно тут - https://www.rstudio.com/products/rstudio/download/

После того как вы установите R и RStudio, открывайте RStudio, в меню идём View -> Panel  - > Show All panels

![](http://img.netpeak.ua/alsey/150970484477_kiss_27kb.png)

Теперь можете вводить команы в окне Source (по умолчанию это правое вернее окно.
![](http://img.netpeak.ua/alsey/150970501494_kiss_21kb.png)

Для того, что запусть выполнение команд выделите нужную часть кода и нажмите Ctr+Enter, либо можно запустить выполнение всего кода сочетанием клавиш Ctrl+Alt+R

Надеюсь я смог ответить на ваш вопрос.

**Comment by selesnow** [comment]
Я так понимаю я могу эту ветку закрывать.
